# Generated by Django 3.2.14 on 2022-08-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='following',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='ShoppingBasket',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
