# Generated by Django 3.2.14 on 2022-07-30 17:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#49b64e', 'green'), ('#e26c2d', 'orange'), ('#8775d2', 'purple')], verbose_name='цвет тега'),
        ),
    ]
