# Generated by Django 3.2.14 on 2022-08-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
