# Generated by Django 3.2.14 on 2022-08-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
    ]
