# Generated by Django 3.2.14 on 2022-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_tag_color'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(db_column='ingredient', through='recipes.RecipeIngredient', to='ingredients.Ingredient', verbose_name='ингредиенты для блюда'),
        ),
    ]
