# Generated by Django 3.2.14 on 2022-09-03 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipeingredient_unique_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0.1, message='ЕИ - не должна быть равна нулю или отрицательным числом!')], verbose_name='количество'),
        ),
    ]
