# Generated by Django 3.2.14 on 2022-09-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20220903_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-user'], 'verbose_name': 'избранное', 'verbose_name_plural': 'избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingbasket',
            options={'ordering': ['-user'], 'verbose_name': 'корзина покупок', 'verbose_name_plural': 'корзины покупок'},
        ),
    ]
