# Generated by Django 3.2.14 on 2022-09-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_auto_20220903_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-user'], 'verbose_name': 'избранное', 'verbose_name_plural': 'объекты избранного'},
        ),
        migrations.AlterModelOptions(
            name='shoppingbasket',
            options={'ordering': ['-user'], 'verbose_name': 'корзина', 'verbose_name_plural': 'объекты списка покупок'},
        ),
    ]
