# Generated by Django 3.2.14 on 2022-09-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial copy'),
        ('recipes', '0005_auto_20220829_2019'),
        ('recipes', '0028_auto_20220904_1117'),
    ]

    operations = [
    ]
